### ISSUE TITLE
Updates & Changes

### ISSUE THREAD

**Issue by clnsdzy** [ezehadaku/Video-Website#1]
Please make the following changes to this project. Tick each task's checkbox to confirm the changes have been implemented.

- [x] Tooltips on icons on navbar. Click the link to see a sample 👉🏾https://materializecss.com/tooltips.html
- [x] Remove spacing between slider and navbar
- [x] Increase the height of the slider `$('.slider').slider({height: 600});`
- [x] Either remove the slider indicators or recolor them to grey.
- [x] Increase the padding/margin around the search bar to make it more prominent.
- [x] For the cards, I will prefer the following content: image, title, date & time, username, chips, play now action button
- [x] Space out the chips section from the `<hr>` line 
- [x] include the footer content in a container
- [x] Align the Quick links to the left
- [x] Copyright should be 2023 Vid.com and a link to your GitHub profile.

On the signup and login page,

- [x] no header 
- [x] no footer
- [x] The input fields, when in focus, should have the same color theme as the entire project.

Leave a comment below if you have any questions.

**Comment by ezehadaku** [comment]
Sir do you mean that I should add header and footer

**Comment by clnsdzy** [comment]
Yes. It should appear on very page.

**Comment by clnsdzy** [comment]
Alright, I've reviewed all the changes you made. You have done a very good job. See if you can the following changes to wrap it up:

- [x] Limit the Card Titles to just two lines
- [x] The `hr` element of the chips inside the cards is not necessary 
- [x] Fix all links on the homepage to redirect to the actual pages they are stated for.
- [x] The 'PLAY NOW' on each card should match the theme color of the entire project.
- [x] For the Footer, use white text color for the Quick Links and its content. It also needs to match the same column as the third card columns above
![error_footer](https://github.com/ezehadaku/Video-Website/assets/51720461/b41d768d-8777-497c-9590-33230d8f0521)
- [x] On the copyright, the 'CORE-TECH' should be a link to the company's GitHub account: Here's the link: [CORE-TECH](https://github..com/coresystechng)

As always, if there's any questions, feel free to ask.
