### ISSUE TITLE
Frontend Pages

### ISSUE THREAD

**Issue by clnsdzy** [ezehadaku/Video-Website#2]
These are the essential pages for your project, at this time:

1. index page: A simple landing page, highlighting the services/products/features you are offering. It should include, but not limited to, the following components:

- [x] NavBar (for desktops)
- [x] NavBar (for mobile)
- [x] slider
- [x] A welcome text & paragraph
- [x] Few details highlighting the services offered
- [x] Some contact info
- [x] A footer

2. Signup/Register page: Users should be able to create new accounts on the platform. Limit the form inputs to 5 fields at most. Keep the form simple.
3. Login Page: Users to be able to log into their accounts. Keep the form simple.

More pages will be added subsequently. This list will be updated when the time comes for that.

Leave a comment below if you have any questions.

**Comment by ezehadaku** [comment]
Done
